# SPDX-FileCopyrightText: © 2019, 2024 Alexandros Theodotou <alex@zrythm.org>
# SPDX-License-Identifier: AGPL-3.0-or-later

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - setup
  - build
  - test
  - deploy

default:
  cache:
    # this number must be bumped every time the dependencies are updated
    - key: configured-cache-1
      paths:
        - venv
    - key: $CI_COMMIT_TIMESTAMP
      paths:
        - rendered
  tags:
    - archlinux
  before_script:
    - source ./venv/bin/activate

configure:
  stage: setup
  script:
    - python3 -m pip install -r requirements.txt
  before_script:
    - python3 -m venv venv
    - source ./venv/bin/activate

build:
  stage: build
  script:
    - make locale
    - make

#test:
  #stage: test
  #script:
    #- make locale
    #- make
    #- linkchecker --ignore-url .*team.html --ignore-url .*join-us.html rendered

deploy-site:
  stage: deploy
  only:
    - master
    - tags
  script:
    - rsync -av --chown $REMOTE_CI_USER:www-data rendered/* $REMOTE_CI_USER@www.zrythm.org:$REMOTE_WWW_SITE_UPLOAD_PATH
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - source ./venv/bin/activate
