image: "alextee12/arch-yaourt"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  script:
    - make locale
    - make

test:
  stage: test
  script:
    - make locale
    - make
    - linkchecker --ignore-url .*team.html --ignore-url .*join-us.html rendered
