<article>
<h3>
<a name="early-alpha-release">Release v0.4.003 (early alpha)</a>
</h3>

<h4>It's here!</h4>
<p>
The first early alpha release version v.0.4.003 is here! This release marks the first official early alpha release and we are inviting everyone to come and test Zrythm. We are also inviting translators, developers and designers to join our team.
</p>

<h5>Features</h5>
<p>
Current features, among others, include
<ul>
  <li>Saving/Loading projects</li>
  <li>Exporting projects</li>
  <li>Arranger</li>
  <li>Piano roll</li>
  <li>Mixer</li>
  <li>Plugin browser</li>
  <li>File browser</li>
  <li>Tracklist</li>
  <li>Toolbox</li>
  <li>Hideable docks</li>
  <li>Repeatable MIDI regions/clips</li>
  <li>Arranger minimap view</li>
  <li>Undo/Redo on most actions</li>
  <li>Automatable channel/plugin parameters</li>
  <li>CPU/DSP usage meters</li>
  <li>Multi-language support</li>
  <li>Status bar</li>
</ul>
</p>

<h5>Windows Support</h5>
<p>
Surprise! Zrythm works on Windows too
<img class="news_img" src="/static/images/windows.png" alt="Windows"/>
</p>

<h5>Try it</h5>
<p>
Although still unstable, Zrythm has a lot of essential features already implemented. Please take it for a test drive and report any bugs, ideas, feedback and suggestions you may have on our <a href="https://git.zrythm.org/zrythm/zrythm/issues">issue tracker</a>. You can also find this link within Zrythm by going to Help->Report a Bug. The manual can be found <a href="https://manual.zrythm.org">here</a>
</p>

<h5>Come Join Us!</h5>
<p>
See <a href="join-us.html">Join Us</a> for IRC rooms, Matrix rooms, mailing lists and more info on how to get involved.
</p>

<h5>Donate</h5>
<p>
If you like Zrythm or would like to support development, please consider <a href="https://liberapay.com/Zrythm/donate">donating</a>. We use LiberaPay, PayPal and Bitcoin. See <a href="join-us">Support Us</a> for more info.
</p>

</article>

