<article>
<h3>
<a id="translation-portal-launched" href="#translation-portal-launched">
  2019-05-04 - {{ _("Translation Portal Launched!") }}</a>
</h3>

<p>
<img class="news_img" src="/static/images/translate.png" alt="Translation Portal"/>
<br>
{% trans %}
Zrythm and all its components are now easily translatable via a
simple web interface.
All you need to do is make an account there and start translating!
If you don't see your language on the list and would like us to include it,
<a href="engage.html">shoot us a message</a>.
{% endtrans %}
</p>

<p>
Happy translating!
</p>

</article>
