<article>
<h3>
<a id="zrythm-translations-hosted-weblate-org" href="#zrythm-translations-hosted-weblate-org">
  2019-06-07 - {{ _("Translations Now Hosted at Weblate.org") }}</a>
</h3>

<p>
{% trans %}
Thanks to the generous hosting provided by the guys at weblate.org,
Zrythm can now be translated there! <a href="https://hosted.weblate.org/engage/zrythm/">
Click Here</a> to get started.
{% endtrans %}
</p>

<p>
{% trans %}
Note: We will be taking down the self-hosted version soon.
{% endtrans %}
</p>

<p>
{% trans %}
Happy translating!
{% endtrans %}
</p>

</article>
