<article>
<h3>
<a id="mailing-lists-up" href="#mailing-lists-up">
  2019-06-19 - {{ _("New Mailing Lists Are Up") }}</a>
</h3>

<p>
{% trans %}
Zrythm has its own mailing lists now <a href="https://lists.zrythm.org">here</a>!
Feel free to subscribe to the <a href="mailto:announce@lists.zrythm.org">announce
mailing list</a> for releases and other announcements!
{% endtrans %}
</p>

<p>
{% trans %}
Developers wishing to discuss Zrythm may use the <a href="mailto:dev@lists.zrythm.org">
dev mailing list</a>.
{% endtrans %}
</p>

<p>
{% trans %}
Likewise, users may use the <a href="mailto:user@lists.zrythm.org">user mailing list</a>.
{% endtrans %}
</p>

<p>
{% trans %}
Archives of past discussions can be found <a href="https://lists.zrythm.org/hyperkitty/">
here</a>.
{% endtrans %}
</p>

</article>

