<article>
<h3>
<a name="translation-portal-launched">Translation Portal Launched!</a>
</h3>

<h4>Translation Made Easy</h4>
<p>
<img class="news_img" src="/static/images/translate.png" alt="Translation Portal"/>
Zrythm and all its components are now easily translatable via a
<a href="https://translate.zrythm.org/projects/zrythm">simple web interface</a>.
All you need to do is make an account there and start translating!
If you don't see your language on the list and would like us to include it,
<a href="/engange.html">shoot us a message</a>.
</p>

<p>
Happy translating!
</p>

</article>
