<footer id="footer">
  <div class="container-fluid cushion-below">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="team.html">{{ _("Developer Team") }}</a></p></li>
            <li><p><a href="contact.html">{{ _("Contact") }}</a></p></li>
            <li><p><a href="about.html">{{ _("About Zrythm") }}</a></p></li>
          </ul>
        </div>
        <div class="col-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="https://git.zrythm.org/zrythm/zrythm/issues">{{ _("Bug Tracker") }}</a></p></li>
            <li><p><a href="https://git.zrythm.org/zrythm/zrythm">{{ _("Source Code") }}</a></p></li>
            <li><p><a href="javascript.html" rel="jslicense">{{ _("JavaScript License Information") }}</a></p></li>
          </ul>
        </div>
        <div class="col-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="https://manual.zrythm.org">{{ _("Manual") }}</a></p></li>
            <li><p><a href="faq.html">{{ _("FAQ") }}</a></p></li>
            <li><p><a href="join-us.html">{{ _("Support Us") }}</a></p></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container text-center">
    <p>
    {% trans %}
    Copyright &copy; Alexandros Theodotou 2019<br>
    This page was created using <a href="https://www.gnu.org/">Free Software</a> only.</br>
    <a href="https://git.zrythm.org/zrythm/zrythm-web">Source code of this site.</a></br>
    Report issues with this website to <a href="https://git.zrythm.org/zrythm/zrythm-web/issues">us</a>.
    {% endtrans %}
    </p>
    <p><em><small>
    </p></em></small>
  </div>
</footer>
