{#
Copyright (C) 2019 Alexandros Theodotou <alex at zrythm dot org>

This file is part of Zrythm

Zrythm is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Zrythm is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.
#}

<header>
  <a href="index.html" class="logo">
    <img class="logo_img" width=28
       src="{{ url('static/images/z.png') }}"
       alt="Logo">
    </img>
  </a>
  <a href="index.html" class="button">Home</a>
  <a href="download.html" class="button">Download</a>
  <a href="reference.html" class="button">Reference</a>
  <a href="community.html" class="button">Community</a>
</header>
